name: "Build & Deploy DEV"

on:
  push:
    branches:
      - 'feature/*'
      - 'fix**'
  pull_request:
    branches:
      - 'develop'

jobs:
  lintGo:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Run GolangCI-Lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.60.3
        format: colored-line-number
        extra_args: --disable-all --enable=errcheck
      continue-on-error: true

  buildGo:
    runs-on: ubuntu-latest
    needs: lintGo

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Go project
      run: go build -v ./...

  sonarQube:
    runs-on: ubuntu-latest
    needs: buildGo
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Go project
      run: go build -v ./...

    - name: Run tests and generate coverage report
      run: go test -v ./... -coverprofile=coverage.out      

    - name: Run SonarQube Scanner
      uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
      with:
        args: |
          -Dsonar.projectKey=bff-golang
          -Dsonar.sources=.
          -Dsonar.go.coverage.reportPaths=coverage.out
          -Dsonar.projectVersion=${{ github.sha }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Create pull request to develop
      if: ${{ success() }}
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ github.head_ref }}
        destination_branch: develop
        pr_title: 'Merge ${{ github.head_ref }} into develop'
        pr_body: 'Automatic pull request created from CI'
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
